# Generated by Django 5.2.6 on 2025-10-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_teacherprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='teacher_code',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
