# Generated by Django 5.2.6 on 2025-11-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_teacher_enrollment'),
        ('users', '0003_alter_teacherprofile_teacher_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, to='courses.course'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, to='courses.course'),
        ),
    ]
