# Generated by Django 5.2.6 on 2026-05-19 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('users', '0005_studentprofile_photo_teacherprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='academics.faculty'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='academics.faculty'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='academics.major'),
        ),
    ]
