# Generated by Django 5.2.6 on 2025-11-15 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_announcement_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='teacher',
        ),
    ]
