# Generated by Django 5.2.6 on 2026-01-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_teacher_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='register',
            field=models.IntegerField(default=0),
        ),
    ]
